<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-3C2U60FS" name="Test2" tests="1" failures="0" timestamp="6 Oct 2017 07:29:58 GMT" time="20.542" errors="0">
  <testcase name="@BeforeTest org_Launch" time="0.0" classname="testNG.UserRegTest">
    <failure type="java.lang.AssertionError" message="Launch Failed expected [welcome] but found [LOGIN]">
      <![CDATA[java.lang.AssertionError: Launch Failed expected [welcome] but found [LOGIN]
	at testNG.TestNGMaster.org_Launch(TestNGMaster.java:34)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest org_Launch -->
  <testcase name="@BeforeClass org_Login" time="0.0" classname="testNG.UserRegTest">
    <skipped/>
  </testcase> <!-- @BeforeClass org_Login -->
  <testcase name="@AfterClass org_Close" time="0.0" classname="testNG.UserRegTest">
    <skipped/>
  </testcase> <!-- @AfterClass org_Close -->
  <testcase name="@AfterClass org_Logout" time="0.0" classname="testNG.UserRegTest">
    <skipped/>
  </testcase> <!-- @AfterClass org_Logout -->
  <testcase name="org_userReg" time="0.002" classname="testNG.UserRegTest">
    <skipped/>
  </testcase> <!-- org_userReg -->
</testsuite> <!-- Test2 -->
